// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Jul 4, 2020 at 12:51:16 PM
// ======================================================


import Foundation


private let AUTO_PLIST_OBJECT0_PATH = Bundle.main.path(forResource: "Object0", ofType: "plist")

private let AUTO_PLIST_OBJECT0_INDEX_ANIMALDATAFINAL = 0   // animalDataFinal
private let AUTO_PLIST_OBJECT0_INDEX_ITEM1 = 1   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM2 = 2   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM3 = 3   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM4 = 4   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM5 = 5   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM6 = 6   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM7 = 7   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM8 = 8   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM9 = 9   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM10 = 10   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM11 = 11   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM12 = 12   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM13 = 13   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM14 = 14   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM15 = 15   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM16 = 16   // 
private let AUTO_PLIST_OBJECT0_INDEX_ITEM17 = 17   // 


class AnimalDataFinalManager {

    public static let sharedManager = AnimalDataFinalManager()
    private init(){}

    private var _object0s = [Object0]()

    func allObject0s() -> [Object0]{

        if _object0s.count > 0 {
            return _object0s
        }

        if let allDatas = NSArray(contentsOfFile: AUTO_PLIST_OBJECT0_PATH!) {

            for array in allDatas {
                guard let array = array as? [AnyObject] else {continue}

                let object0 = Object0()
                object0.animalDataFinal = array[AUTO_PLIST_OBJECT0_INDEX_ANIMALDATAFINAL] as? String // animalDataFinal
                object0.item1 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM1] as? String // 
                object0.item2 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM2] as? String // 
                object0.item3 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM3] as? String // 
                object0.item4 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM4] as? String // 
                object0.item5 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM5] as? String // 
                object0.item6 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM6] as? String // 
                object0.item7 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM7] as? String // 
                object0.item8 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM8] as? String // 
                object0.item9 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM9] as? String // 
                object0.item10 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM10] as? String // 
                object0.item11 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM11] as? String // 
                object0.item12 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM12] as? String // 
                object0.item13 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM13] as? String // 
                object0.item14 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM14] as? String // 
                object0.item15 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM15] as? String // 
                object0.item16 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM16] as? String // 
                object0.item17 = array[AUTO_PLIST_OBJECT0_INDEX_ITEM17] as? String // 
                _object0s.append(object0)
            }
        }
        return _object0s
    }
}