// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Jul 4, 2020 at 12:51:16 PM
// ======================================================


import Foundation


class Object0 {
    var animalDataFinal : String? = nil; // animalDataFinal
    var item1 : String? = nil; // 
    var item2 : String? = nil; // 
    var item3 : String? = nil; // 
    var item4 : String? = nil; // 
    var item5 : String? = nil; // 
    var item6 : String? = nil; // 
    var item7 : String? = nil; // 
    var item8 : String? = nil; // 
    var item9 : String? = nil; // 
    var item10 : String? = nil; // 
    var item11 : String? = nil; // 
    var item12 : String? = nil; // 
    var item13 : String? = nil; // 
    var item14 : String? = nil; // 
    var item15 : String? = nil; // 
    var item16 : String? = nil; // 
    var item17 : String? = nil; // 
}